casn = {
    '75-07-0': ['acetaldehyde', 'acetic aldehyde', 'ethanal', 'ethyl aldehyde', 'nsc 7594'],
    '53-96-3': ['acetamide, n-9h-fluoren-2-yl-', 'acetamide, n-fluoren-2-yl-', 'n-9h-fluoren-2-ylacetamide', '2-aaf', '2-acetamidofluorene', 'faa', 'n-2-fluorenylacetamide', '2-faa', '2-(acetylamino)fluorene', 'nsc 12279'],
    '79-06-1': ['2-propenamide', 'acrylamide', 'acrylic amide', 'propenamide', 'ethylenecarboxamide', 'vinyl amide', 'bio-acrylamide 50', 'nsc 7785', 'dm 206', 'a 108465', 'aladdin a 108467', '2-propenamide, olymer with graphene, graft'],
    '107-13-1': ['2-propenenitrile', 'acrylonitrile', 'acrylon', 'carbacryl', 'cyanoethylene', 'fumigrain', 'propenenitrile', 'vcn', 'vinyl cyanide', 'ventox', 'cyanoethene', 'nsc 6362'],
    '15972-60-8': ['acetamide, 2-chloro-n-(2,6-diethylphenyl)-n-methoxymethyl)-', "acetanilide, 2-chloro-2'6'-diethyl-n-(methoxymethyl)-", '2-chloro-n-(2,6-diethylphenyl)-n-(methoxymethyl)acetamide', 'cp 50144', 'lasso', "2-chloro-2'6'-diethyl-n-methoxymethylacetanilide", "2'6'-diethyl-n-(methoxymethyl)-2-chloroacetanilide", 'alachlor', 'metachlor', 'methachlor', 'lasagrin', 'nitala', 'alapaz', 'satochlor', 'lazo', 'perfect', 'micro-tech', 'alanex', 'perfect (herbicide)', 'lasso microtech', 'intro'],
    '309-00-2': ['1,4:5,8-dimethanonaphtalene, 1,2,3,4,10,10-hexachloro-1,4,4a,5,8,8a-hexahydro-, (1r,4s,4as,5s,8r,8ar)-rel-', '1,4:5,8-Dimethanonaphthalene, 1,2,3,4,10,10-hexachloro-1,4,4a,5,8,8a-hexahydro-, (1α,4α,4aβ,5α,8α,8aβ)', '1,4:5,8-Dimethanonaphthalene, 1,2,3,4,10,10-hexachloro-1,4,4a,5,8,8a-hexahydro0,endo,exo-', 'rel-(1r,4s,4as,ss,8r,8ar)-1,2,3,4,10,10-hexachloro-1,4,4a,5,8,8a-hexahydro-1,4:5,8-dimethanonaphthalene', 'ent 15949', 'ent 15,949', 'aldrin', 'compund 118', '1,2,3,4,10,10-hexachloro-1,4,4a,5,8,8a-hexahydro-1,4-endo-exo-5,8-dimethanonaphthalene', '1,2,3,4,10,10-hexachloro-1,4,4a,5,8,8a-hexahydro-endo-1,4-exo-5,8- dimethanonaphthalene', 'hhdn', 'octalene', 'seedrin', 'tatuzinho', 'sd 2794', 'aldocit', 'kortofin', 'aldrex 40', 'aldrex 25', 'andrex 40', 'andrex', 'aldrine'],
    '107-05-1': ['1-propene, 3-chloro-', 'propene, 3-chloro-', '3-chloro-1-propene', 'allyl chloride', '1-chloro-2-propene', '3-chloropropylene', '3-chloropropene', '2-propenyl chloride', 'nsc 20939', 'hco 1260zf'],
    '92-67-1': ["[1,1'-biphenyl]-4-amine", '4-biphenylamine', 'p-aminobiphenyl', '4-aminobiphenyl', 'p-aminodiphenyl', '4-aminodiphenyl', 'p-phenylaniline', 'xenylamine', 'p-biphenylamine', 'p-xenylamine', '4-biphenylylamine', '4-phenylaniline', '4-phenylbenzenamine', "(1,1'-biphenyl-4-yl)amine", 'nsc 7660', "4-amino-1,1'-biphenyl", 'p-aminophenyl benzene'],
    '62-53-3': ['benzenamine', 'aniline', 'c.i. 76000', 'aminophen', 'benzene, amino-', 'blue oil', 'phenylamine', 'anyvim', 'aminobenzene', 'nci 176889'],
    '84-65-1': ['9,10-anthracenedione', 'anthraquinone', 'hoelite', '9,10-anthraquinone', 'anthradione', 'morkit', 'anthracene-9,10-quinone', 'daq-n', 'flight control', 'nsc 7957', 'flight control plus', '1,4,11,12-tetrahydro-9,10-anthraquinone', 'saq', 'kawasaki saq', 'saq (quinone)', 'avipel', 'dble 104'],
    '7440-38-2': ['arsenic', 'arsenic-75', 'arsenic black'],
    '1912-24-9': ['1,3,5-triazine-2,4-diamine,6-chloro-n^2-ethyl-n^4-(1-methylethyl)-', 's-triazine,2-chloro-4-(ethlamino)-6-(isopropylamino)-', "1,3,5-triazine-2,4-diamine,6-chloro-n-ethyl-n'-(1-methylethyl)-", '6-chloro-n^2-ethyl-n^4-(1-methylethyl)-1,3,5-triazine-2,4-diamine', 'a 361', 'g 30027', 'aktinit a', 'atrazine', '2-chloro-4-ethylamineisopropylamine-s-triazine', '1-chloro-3-ethylamino-5-isopropylamino-2,4,6-triazine', 'hungazin pk', 'triazine a 1294', 'gesaprim', 'zeazin', '2-ethylamino-4-isopropylamino-6-chloro-s-triazine', 'hungazin', '2-chloro-4-(ethylamino)-6-(isopropylamino)-s-triazine', 'argezine', 'aktikon', 'aktikon pk', 'atrazin', '2-chloro-4-(ethylamino)-6-(2-propylamino)-s-triazine', 'aktinit pk', 'cyazin', 'wonuk', 'primatol a', '2-chloro-4-(ethylamino)-6-(isopropylamino)triazine', 'oleogesaprim', 'zeazine', 'chromozin', 'radazin', 'gesaprim 50', 'akticon', 'atrataf', 'zeapos', 'cet', 'oleogesaprim 200', 'gesaprim 500', 'herbatoxol', 'atz', 'zeopos', '6-chloro-4-(ethylamino)-2-(isopropylamino)-s-triazine', 'gesaprim L', 'azoprim', 'azoprim 50', 'aatrex nine-o', 'aatrex 4l', 'aatrex' 'gesamprim', 'zealin l', 'atranex', 'atranex 80wp', 'nu-trazine', 'aatrex 4lc', 'radazin t', 'nsc 163046', 'prioleo', 'atraphyt', 'atragranz', 'farmozine', "6-chloro-n-ethyl-n'-(1-methylethyl)-1,3,5-triazine-2,4-diamine", 'atrasan', 'aatrex l', 'nortox 500sc', '2-ethylamino-4-isopropylamino-6-chloro-1,3,5-triazine', 'atrazerba fl', 'atradex', 'aatrax', 'atanor 50 sc', '2-chloro-6-ethylamino-4-isopropylamino-1,3,5-triazine', 'proof', 'maizal surcos', 'maizal'],
    '492-80-8': ["benzenamine, 4,4'-carbonimidoylbis[n,n-dimethyl-", 'c.i. solvent yellow 34', "4,4'-carbonimidoylbis[n,n-dimethylbenzenamine]", 'c.i. 41000b', 'auramine n base', 'auramine o base', 'auramine ss', 'brilliant oil yellow', "4,4'-dimethylaminobenzophenonimide", 'waxoline yellow o', 'auramine base', 'auramine oaf', 'baso yellow 124', 'orient oil yellow 101', "4,4'-(imidocarbonyl)bis(n,n-dimethylaniline)", 'solvent yellow 34', 'auramine s'],
    '103-33-3': ['diazene, 1,2-diphenyl-', 'azobenzene', 'diazene, diphenyl-', 'benzene, azo-', '1,2-diphenyldiazene', 'azobenzide', 'azobenzol', 'benzeneazobenzene', 'diphenyldiimide', 'benzene, azobis-', 'diphenyldiazene', 'phenylazobenzene', 'a 15073', 'nsc 2102'],
    '100-52-7': ['benzaldehyde', 'benzenecarbonal', 'benzenecarboxaldehyde', 'benzoic aldehyde', 'phenylmethanal', 'artificial almond oil', 'benzaldehyde ffc', 'phenylformaldehyde', 'nsc 7917', 'benzoic acid aldehyde'],
    '71-43-2': ['benzene', 'benzol', 'coal naphtha', 'cyclohexatriene', 'phene', 'henyl hydride', 'pyrobenzol', 'benzole', 'pyrobenzole', '[6]annulene', '1,3,5-cyclohexatriene', 'nsc 67315'],
    '6369-59-1': ['1,4-benzenediamine, 2-methyl-, sulfate (1:?)', 'toluene-2,5-diamine, sulfate', '1,4-benzenediamine, 2-methyl-, sulfate', 'c.i. 76043', 'c.i. oxidation base 4', 'fouramine std', 'p-toluenediamine sulfate', '2,5-diaminotoluene sulfate', 'p-toluylenediamine sulfate'],
    '92-87-5': ["[1,1'-biphenyl]-4,4'-diamine", 'benzidine', "4,4'-biphenyldiamine", 'c.i. azoic diazo component 112', "4,4'-diaminobiphenyl", 'p-diaminodiphenyl', "4,4'-diphenylenediamine", 'fast corinth base b', "4,4'-bianiline", "4,4'-diaminodiphenyl", "p,p'-diaminodiphenyl", "p,p'-bianiline", "4,4'-diamino-1,1'-biphenyl", "4'-amino-[1,1'-biphenyl]-4-ylamine", '4-(4-aminophenyl)aniline', 'nsc 146476', "4,4'-diaminobenzidine"],
    '98-07-7': ['benzene, (trichloromethyl)-', 'toluene, α,α,α-trichloro-', '(trichloromethyl)benzene', 'benzenyl trichloride', 'benzotrichloride', 'benzylidyne chloride', 'phenylchloroform', 'toluene trichloride', 'α,α,α-trichlorotoluene', 'ω,ω,ω-trichlorotoluene', 'benzenyl chloride', 'benzyl trichloride', 'phenyltrichloromethane', '1-(trichloromethyl)benzene', 'trichlorophenylmethane', 'nsc 14663'],
    '100-44-7': ['benzene, (chloromethyl)-', 'toluene, α-chloro-', '(chloromethyl)benzene', 'benzyl chloride', 'ω-chlorotoluene', 'chlorophenylmethane', 'tolyl chloride', 'α-chlorotoluene', 'phenylmethyl chloride', 'nsc 8043', '1-chloromethylbenzene', 'bnol'],
    '92-52-4': ["1,1'-biphenyl", 'biphenyl', 'diphenyl', 'phenylbenzene', 'bibenzene', "1,1'-diphenyl", 'tetrosin ly', 'carolid al', 'nsc 14916'],
    '111-44-4': ["ethane, 1,1'-oxybis[2-chloro-", 'ether, bis(2-chloroethyl)', 'ether, bis(chloroethyl)', "1,1'-oxybis[2-chloroethane]", 'bis(β-chloroethyl) ether', 'bis(2-chloroethyl) ether', 'chlorex', '1-chloro-2-(β-chloroethoxy)ethane', 'dcee', "2,2'-dichlorethyl ether", "β,β′-dichloroethyl ether", 'di(β-chloroethyl) ether', "β,β′-dichlorodiethyl ether", "2,2'-dichlorodiethyl ether", "2,2'-dichloroethyl ether", 'sym-dichloroethyl ether', '2-chloroethyl ether', '1,5-dichloro3-oxapentane', 'diethylene glycol dichloride', 'oxygen mustard', '1-chloro-2-(2-chloroethoxy)ethane', '2-(2-chloroethoxy)ethyl chloride', 'di-2-chloroethyl ether', 'nsc 406647', 'bcee'],
    '542-88-1': ["methane, 1,1'-oxybis[1-chloro-", 'ether, bis(chloromethyl)', 'methane, oxybis[chloro-', "1,1'-oxybis[1-chloromethane]", 'bis(chloromethyl) ether', 'chloromethyl ether', 'sym-dichloromethyl ether', 'dichlorodimethyl ether', "α,α′-dichlorodimethyl ether", 'monochloromethyl ether', 'oxybis[chloromethane]', 'bcme'],
    '15541-45-4': ['bromate', 'bromic acid, ion(1-)', 'bromate (bro3-)', 'bromate ion', 'bromate (bro31-)', 'bromate ion (bro3-)', 'bromate(1-)', 'bromate ion (bro310)', 'bromate (bro3(1-))'],
    '75-27-4': ['methane, bromodichloro-', 'bromodichloromethane', 'dichlorobromomethane', 'monobromodichloromethane', 'dichloromonobromomethane', 'nsc 8018', 'bdcm'],
    '75-25-2': ['methane, tribromo-', 'tribromomethane', 'bromoform', 'methenyl tribromide', 'nsc 8019'],
    '106-94-5': ['propane, 1-bromo-', '1-bromopropane', 'propyl bromide', 'n-propyl broide', 'leksol', 'ascusol mc', '1-propyl bromide', 'drysolv', '3-bromopropane', 'abzol jg', 'ps cleaner'],
    '1689-84-5': ['benzonitrile, 3,5-dibromo040hydroxy-', '3,5-dibromo-4-hydroxybenzonitrile', 'bromoxynil', 'broxynil', '4-hydroxy-3,5-dibromobenzonitrile', 'brominal', '2,6-dibromo-4-cyanophenol', 'labuctril', '4-cyano-2,6-dibromophenol', 'labuctril 25', 'pardner', 'brominil', 'toplan', 'me 4 brominal', 's 2132', 'sabre', '1-cyano-3,5-dibromo-4-hydroxybenzene', 'emblem'],
    '1689-99-2': ['octanoic acid, 2,6-dibromo-4-cyanophenyl ester', 'octanoic acid, ester with 3,5-dibromo-4-hydroxybenzonitrile', 'bromoxynil octanoate', 'bromoxynil n-octanoyl ester', '3,5-dibromo-4-n-octanoyloxybenzonitrile', 'bromoxynil octanoic acid ester', '4-cyano-2,6-dibromophenyl octanoate', '3,5-dibromo-4-octanoyloxybenzonitrile', 'nph 1320', '2,6-dibromo-4-cyanophenyl octanoate', '3,5-dibromo-4-hydroxybenzonitrile octanoate ester', 'brominal 2', 'buctril', 'certrol b', 'bromotril', 'buctril 33.4ec'],
    '106-99-0': ['1,3-butadiene', 'biethylene', 'bivinyl', 'α,γ-butadiene', 'divinyl', 'erythrene', 'vinylethylene', 'butadiene', 'butadiene-1,3'],
    '75-65-0': ['2-propanol, 2-methy-', 'tert-butyl alcohol', '2-methyl-2-propanol', 'tert-butanol', '1,1-dimethylethanol', 'trimethylcarbinol', 'trimethylmethanol', 't-butanol', '2-hydroxy-2-methylpropane', 'tert-bu-oh', '2-methylpropan-2-ol', 't-buoh'],
    '25013-16-5': ['phenol, (1,1-dimethylethyl)-4-methoxy-', 'phenol, tert-butyl-4-methoxy-', '(1,1-dimethylethyl)-4-methoxyphenol', 'butylated hydroxyanisole', 'bha', 'butylhydroxyanisole', 'tert-butylhydroxyanisole', 'tert-butyl-4-hydroxyanisole', 'antioxyne b', 'embanox', 'protex', 'tert-butyl-p-hydroxyanisole', 'sustane 1f', 'tert-butyl-4-methoxyphenol', '2(3)-tert-butyl-4-hydroxyanisole', 'tenox bha', 'boa (antioxidant)', 'boa', 'bha (antioxidant)', 'e 320', 'grindox bha', 'tert-butyl-p-hydroxyanisol'],
    '128-37-0': ['phenol, 2,6-bis(1,1-dimethylethyl)-4-methyl-', 'p-cresol, 2,6-di-tert-butyl-', '2,6-bis(1,1-dimethylethyl)-4-methylphenol', 'cao 1', 'cao 3', 'dalpac', 'dbpc', 'deenax', '2,6-di-tert-butyl-p-methylphenol', '4-hydroxy-3,5-di-tert-butyltoluene', 'impruvol', 'ionol', 'ionole', '4-methyl-2,6-di-tert-butylphenol', 'parabar 441', 'sustane bht', 'tenamene 3', 'topanol oc', 'vianol', 'bht', 'butylated hydroxytoluene', 'topanol o', 'topanol', 'dibunol', 'nonox tbc', 'ao 4k', 'dibutylated hydroxytoluene', 'ionol 1', 'buks', '2,6-di-tert-butylcresol', 'stavox', 'di-tert-butyl-4-methylpheenol', 'o-di-tert-butyl-p-methylphenol', 'di-tert-butyl-p-cresol', 'antioxidant 4k', 'sumilizer bht', 'di-tert-butylcresol', 'catalin cao 3', 'chemanox 11', 'vanlube pcx', 'vanlube pc', 'advastab 401', '2,6-di-tert-butyl-p-cresole', 'antioxidant 29', 'ao 29', 'antioxidant 30', 'p 21', 'antioxidant dbpc', 'agidol', 'alkofen bp', 'kerabit', 'agidol 1', 'ao 4', 'vulkanox kb', '2,6-di-tert-butylmethylphenol', 'nocrac 200', '2,6-di-tert-butyl-4-hydroxytoluene', '2,6-di-tert-butyl-4-methyl-1-hydroxybenzene', 'ionol bht', 'aox 4', 'aox 4k', 'antioxidant 4', 'tenox bht', 'topanol bht', 'swanox bht', '2,6-di-tert-butyl-4-methylhydroxybenzene', 'antioxidant 264', 'vanox pc', 'antage bht', '3,5-di-tert-butyl-4-hydroxytoluene', 'popol', 'ralox bht', 'permanax bht', 'antioxidant mpj', 'topanol ol', 'naugard bht', '2,6-di-tert-butyl-p-cresol', 'bat', 'ultranox 226', 'lubrizol 817', '2,6-di-tert-butyl-4-methylpheno', 'p 21 (phenol)', 't 501', 'ionol 330', 'yoshinox bht', '2,6-bis(tert-butyl)-4-methylphenol', '2,6-tert-butyl-4-methylphenol', 'antox qt', 'ionol k', 'ionol cp', '4-methyl-2,6-bis(1,1-dimethylethyl)phenol', 't 501 (phenol)', 'antioxidant t 501', 'bht 264', 'lowinox bht', 'selosol h 633', 'tonarol', 'bht-c', 'e 321', 'dibutylcresol', 'dibutylhydroxytoluene', 'nsc 6347', 'nocrac 2000', '2,6-di-tert-butyl-4-cresol', 'topanol o-fg', 'sumilizer bht-r', 'bht swanox', 'agidol 1a', '2,6-di(tert-butyl)hydroxytoluene', 'b-nox bht-', 'nipanox', 'k-nox-bht', '3,5-di-tert-butyl-p-hydroxytoluene', 'grindox bht', '4-methyl-2,6-ditertbutyl phenol', 'fg', 'addiox 1005', '2,6-di-t-butyl-4-methylphenol', '2,6-ditertbutyl paracresol', 'topanol c', '2,6-di-tert-butyl-p-cresol', 'vulkanox bht', 'na-lube ao 220', 'dibutyl paracresol', 'additin rc 1220', 'pn 01', 'm 4801', 'antioxidant 501', 'bht 501', 'lavinix bht', 'nipanox bht', 'h-bht', 'antioxidant oc', '3,5-bis(1,1-dimethylethyl)-4-hydroxytoluene', 'antioxidant bht', 't 502a', 'nk-bht', '2,6-di-tert-butyl-4-methyl phenol', 'nocrac sp-n', 'ao 246', 'chinox bht', 'antioxidant 502a', 'k-nox bht-p', 'antiager 264', 'antioxidant 1005', 'dw 3432 (phenol)', 'dw 3432', 'st-4-1'],
    '2425-06-1': ['1h-isoindole-1,3(2h)-dione, 3a,4,7,7a-tetrahydro-2-[(1,1,2,2-tetrachloroethyl)thio]-', '4-cyclohexene-1,2-dicarboximide, n-[(1,1,2,2-tetrachloroethyl)thio]-', '3a,4,7,7a-tetrahydro-2-[(1,1,2,2-tetrachloroethyl)thio]-1h-isoindole-1,3(2h)-dione', 'ortho 5865', 'n-1,1,2,2-tetrachloroethylmercapto-4-cyclohexene-1,2-dicarboximide', 'n-(1,1,2,2-tetrachloroethylthio)-4-cyclohexene-1,2-dicarboximide', 'captafol', 'cs 5623', 'tetrachloroethylthiotetrahydrophthalimide', 'n-(1,1,2,2-tetrachloroethylthio)-4-cyclohexene-1,2-dicarboxyimide', 'n-(tetrachloroethylthio)tetrahydrophthalimide', 'folcid', 'difolatan', 'difolatan 4f1', 'haipen 50', 'alfloc 7020', 'nalco 7046', 'proxel ef', 'alfloc 7046', 'n-(1,1,2,2-tetrachloroethylthio)-Δ4-tetrahydrophthalimide', 'terrazol', 'difolatan 4f', 'arborseal', 'difolatan bow', 'foltaf', 'santar sm', 'merpafo', 'difolatan 80w', 'sanspor'],
    '133-06-2': ['1h-isoindole-1,3(2h)-dione, 3a,4,7,7a-tetrahydro-2-[(trichloromethyl)thio]-', '4-cyclohexene-1,2-dicarboximide, n-[(trichloromethyl)thio]-', '3a,4,7,7a-tetrahydro-2-[(trichloromethyl)thio]-1h-isoindole-1,3(2h)-dione', 'sr 406', 'amercide', 'captan', 'flit 406', 'fungus ban type ii', 'orthocide 7.5', 'orthocide 406', 'orthocide', 'stauffer captan', 'n-trichloromethylmercapto-4-cyclohexene-1,2-dicarboximide', 'n-[(trichloromethyl)thio]-4-cyclohexene-1,2-dicarboximide', 'n-[(trichloromethyl)thio]tetrahydrophthalimide', 'n-trichloromethylthio-3a,4,7,7a-tetrahydrophthalimide', 'vancide 89', 'vangard k', 'esso fungicide 406', 'malipur', 'captan 50w', 'neracid', 'captaf 85w', 'orthocide 50', 'glyodex 37-22', 'vancide 89re', 'n-trichloromethylthio-4-cyclohexene-1,2-dicarboximide', 'orthocide 75', 'orthocide 83', 'aacaptan', 'kaptan', 'captaf', 'captex', 'merpan', 'hexacap', 'n-[(trichloromethyl)thio]-Δ4-tetrahydrophthalimide', 'osocide', 'bangton', 'trimegol', 'rallis captaf', 'buvisild k', 'captadin', 'deltan', 'radocaptan', 'captab', 'orthocide 75w', 'orthocide s 50', 'orthocide 83rp', 'kaptazor', 'zenecal', 'bangtan', 'ugecap 83', 'ugecap', 'nsc 36726', 'captan 4l', 'venturin', 'micro-chek 12', 'crystal 50', 'crystal 50 wdg', 'captan 50wp', 'kaptan 50wp', 'kejundan', 'captan 80wdg', '2-[(trichloromethyl)sulfanyl]-2,3,3a,4,7,7a-hexahydro-1h-isoindole-1,3-dione', 'merpan 80wdg', 'merpan 480sc'],
    '56-23-5': ['methane, tetrachloro-', 'carbon tetrachloride', 'tetrachloromethane', 'benzinoform', 'necatorina', 'perchloromethane', 'carbon chloride (ccl4)', 'tetrafinol', 'tetraform', 'carbona', 'tetrasol', 'flukoids', 'univerm', 'vermoestricid', 'r 10 (refrigerant)', 'r 10', 'halon 1040', 'cc m0', 'nsc 97063', 'phenixin', '1,1,1,1-tetrachloromethane', 'phenoxin'],
    '118-75-2': ['2,5-cyclohexadiene-1,4-dione, 2,3,5,6-tetrachloro-', 'p-benzoquinone, 2,3,5,6-tetrachloro-', '2,3,5,6-tetrachloro-2,5-cyclohexadiene-1,4-dione', 'ent 3797', 'chloranil', 'dow seed disinfectant no. 5', 'reranil', 'spergon i', 'spergon', 'spergon technical', 'tetrachlorobenzoquinone', 'tetrachloro-p-benzoquinone', '2,3,5,6-tetrachloro-1,4-benzoquinone', 'tetrachloroquinone', 'tetrachloro-p-quinone', 'vulklor', 'p-chloranil', 'coversan', 'tetrachloro-1,4-benzoquinone', '2,3,5,6-tetrachlorobenzoquinone', '2,3,5,6-tetrachloro-p-benzoquinone', '2,3,5,6-tetrachloroquinone', 'quinone tetrachloride', 'α-chloranil', 'psorisan', 'actor cl', '2,3,5,6-tetrachlorocyclohexadiene-1,4-dione', '1,2,4,5-tetrachlorobenzoquinone', 'nsc 8432', '2,3,5,6-tetrachloro-1,4-(p-)-benzoquinone'],
    '12789-03-6': ['chlordane', 'technical chlordane', 'belt', 'chlor kil', 'corodane', 'chlordan', 'kypchlor', 'intox (insecticide)', 'intox', 'unexan-koeder', 'starchlor', 'ortho-klor', 'octachlor', 'termex', 'sydane', 'chlorotox', 'octachlordane'],
    
}

def casn_search(analyte):
    if analyte in casn:
        return analyte
    poss_casn = [key for key, val in casn.items() if analyte.lower() in val]
    if len(poss_casn) == 0:
        raise FileNotFoundError
    else:
        return poss_casn

#while True:
    #x = input('search analyte: ')
    #if x.lower() == 'exit':
        #break
    #try:
        #print(casn_search(x))
    #except FileNotFoundError:
        #print('analyte not found')